apiVersion: apps/v1
kind: Deployment
metadata:
  name: incidentdetectorservice
  labels:
    app: incident-detector
spec:
  replicas: 0
  selector:
    matchLabels:
      app: incident-detector
      tier: web
  template:
    metadata:
      labels:
        app: incident-detector
        tier: web
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8077"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: incident-detector-app
        image: index.docker.io/kemmyxy/incident_detector:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        command: ["python"]
        args: ["incident_detector.py"]
        resources:
          requests: 
            cpu: 200m