---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: shippingservice-fault-injection-2
spec:
  hosts:
    - shippingservice
  http:
    - fault:
        delay:
          fixedDelay: .2s
          percent: 100
      match:
        - sourceLabels:
            app: checkoutservice
      route:
        - destination:
            host: shippingservice
    - fault:
        delay:
          fixedDelay: 0.4s
          percent: 100
      match:
        - uri:
            regex: .*/GetQuote
      route:
        - destination:
            host: shippingservice
    - route:
        - destination:
            host: shippingservice