{
 "title": "lab7",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "y_min, y, y_max monitor-checkoutservice-shippingservice",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "lab7_checkoutservice_2_shippingservice_y{app=\"monitor-checkoutservice-shippingservice\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "lab7_checkoutservice_2_shippingservice_y_maximum{app=\"monitor-checkoutservice-shippingservice\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "lab7_checkoutservice_2_shippingservice_y_minimum{app=\"monitor-checkoutservice-shippingservice\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "y_min, y, y_max frontend-checkoutservice-shippingservice",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "lab7_frontend_2_shippingservice_y{app=\"monitor-frontend-shippingservice\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "lab7_checkoutservice_2_shippingservice_y_maximum{app=\"monitor-checkoutservice-shippingservice\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "lab7_checkoutservice_2_shippingservice_y_minimum{app=\"monitor-checkoutservice-shippingservice\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Severity 1 Incidents ",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sev1{app=\"incident-detector\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Severity 2 Incidents ",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sev2{app=\"incident-detector\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lab7 Temperature ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "temperature{app=\"incident-detector\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Accumulator 1 and Accumulator 2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "accumulator1{app=\"incident-detector\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "accumulator2{app=\"incident-detector\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "anomaly count gauge monitor-frontend-shippingservice",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "lab7_frontend_2_shippingservice_Anomaly_Count{app=\"monitor-frontend-shippingservice\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "anomaly count gauge monitor-checkoutservice-shippingservice",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "lab7_checkoutservice_2_shippingservice_Anomaly_Count{app=\"monitor-checkoutservice-shippingservice\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "request durations for frontend_shippingservice",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(istio_request_duration_milliseconds_bucket{app=\"monitor-frontend-shippingservice\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " request durations for checkoutservice_shippingservice",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(istio_request_duration_milliseconds_bucket{app=\"monitor-checkoutservice-shippingservice\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MAE/MAPE score gauges monitor-frontend-shippingservice",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "lab7_frontend_2_shippingservice_MAE_Gauge{app=\"monitor-frontend-shippingservice\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "lab7_frontend_2_shippingservice_MAPE_Gauge{app=\"monitor-frontend-shippingservice\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MAE/MAPE score gauges monitor-checkoutservice-shippingservice",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "lab7_checkoutservice_2_shippingservice_MAE_Gauge{app=\"monitor-checkoutservice-shippingservice\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "lab7_checkoutservice_2_shippingservice_MAPE_Gauge{app=\"monitor-checkoutservice-shippingservice\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time series of  chosen quantiles of the two services",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(istio_request_duration_milliseconds_bucket{app=\"monitor-checkoutservice-shippingservice\"}[1m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(istio_request_duration_milliseconds_bucket{app=\"monitor-frontend-shippingservice\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}